name: Deploy Nginx App

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing git pull and pm2 restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script:  cd /root/scripts/;pwd; tmux new -d -s  ${{ github.event.head_commit.message }} "/bin/bash client_deploy.sh";
